title: "DOC's Space"
description: Here you can find everything you don't need.
author:
  name: DOC

exclude:
  - .gitignore
  - README.md
  - Makefile
  - .ruby-version
  - Gemfile
  - vendor # jekyll posts fuck off.

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
