title: "DOC's Space"
description: Here you can find everything you don't need.
author:
  name: DOC
repository: DOCtorActoAntohich/doctoractoantohich.github.io

exclude:
  - .gitignore
  - README.md
  - Makefile
  - .ruby-version
  - Gemfile
  - vendor # jekyll posts fuck off.

plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at

whitelist:
  - jekyll-redirect-from
