exclude:
  - ".gitignore"
  - "README.md"
  - ".ruby-version"
  - "Makefile"

title: "DOC's Space"
description: Here you can find everything you don't need.
author:
  name: DOC

include:
  - content

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from